services:
  
  sciky-thinker-test: 
    image: scikit-thinker-test
    build: 
      context: ./src
      dockerfile: Dockerfile
      platform: linux/arm64
    container_name: scikit-thinker-test
    volumes: 
      - ./src:/workspace
    network_mode: host
    env_file:
      - .env  
    restart: always
